test:
  image: python:3.6
  variables:
    LC_ALL: C.UTF-8
    LANG: C.UTF-8
  script:
    - apt-get update -qy
    - apt-get install -y python3-pip
    - pip install -r requirements.txt
    - pip install -r requirements-dev.txt
    - python setup.py test
